### PR TITLE
[WIP] CoreCLR 2.0 port

### PR DESCRIPTION
**Pull request by ethanhs**
This is the beginning of my work on moving Pyjion to CoreCLR 2.0. Currently I am having some issues with the "real jit" not existing, but I just need to read through things a bit more. I just wanted to put this out there and get feedback (if there is any) on my work so far.

__WIP - DO NOT MERGE__

After this (hopefully) gets merged, I will move on to porting to a cmake build system.

### CODE REVIEW

**Comment by brettcannon** [comment]
Closing as this has already occurred.

**Comment by ethanhs** [comment]
Thanks. I think I will work on #76 now instead :)

**Comment by DinoV** [comment]
Actually we are still on CoreCLR 1.0 - I was planning on using this as the starting point to get 2.0 going.  We need to upgrade our Clang version to 3.9 which is used w/ CoreCLR 2.0 to get math overflow intrinsics, which should give us parity w/ Windows, and make me feel like we're ready to merge the linux branch to master.  So I'm re-opening

**Comment by ethanhs** [comment]
@DinoV 2.1 shipped at the end of last month so maybe we should target that? IIRC I got caught up in some weird API change in ICorJitInfo that I didn't have time to figure out. Updating to CoreCLR 2 would be great because then things will work out of the box with VS 2017.

**Comment by DinoV** [comment]
This now got merged plus additional commits to get it all working and updated to 2.1.1

**Pull request closed without merging**
